### ISSUE TITLE
Error message: Unsupported operand types

### ISSUE THREAD

**Issue by pbchase** [ctsit/form_render_skip_logic#37]
luca.pizzato reports on 2018-09-12:

> Hello,
> 
> i have a problem with the update of the form skip logic.
> 
> When i try to use the Advanced control mode (it works in standard), even with a simple logic [baseline_arm_1][sex] = '1' it goes on fatal error like this:
> 
> REDCap crashed due to an unexpected PHP fatal error!
> 
>     Error message: Uncaught Error: Unsupported operand types in 
>     /var/www/html/update/modules/form_render_skip_logic_v3.3.3/ExternalModule.php:308 
> 
>     Stack trace:
>     #0 /var/www/html/update/modules/form_render_skip_logic_v3.3.3/ExternalModule.php(373):
>        FormRenderSkipLogic\ExternalModule\ExternalModule->getFormsAccessMatrix(113,NULL) 
>     #1 /var/www/html/update/modules/form_render_skip_logic_v3.3.3/ExternalModule.php(51):
>        FormRenderSkipLogic\ExternalModule\ExternalModule->loadFRSL('record_home',NULL) 
>     #2 [internal function]:FormRenderSkipLogic\ExternalModule\ExternalModule->redcap_every_page_top('36')
>     #3 /var/www/html/update/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(1320): 
>        call_user_func_array(Array, Array) 
>     #4 /var/www/html/update/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(1405):
>        ExternalModules\ExternalModules::startHook('form_render_ski...', 'v3.3.3',Array) 
>     #5 /var/www/html/update/redcap_v8.5.11/Classes/Hooks.php(37):
>        ExternalModules\ExternalModules::callHook('every_page_top', Array) 
>     #6 /var/www/html/u
> 
>     File: /var/www/html/update/modules/form_render_skip_logic_v3.3.3/ExternalModule.php
>     Line: 308
> 
> this is an installation of REDCap where i use custom hooks too. maybe some problems with it?
> 
> Thanks,
> 
> Luca

**Comment by jasonlones** [comment]
Hello,

We are getting the same or similar error message:

[This message was automatically generated by REDCap]

The 'hook_every_page_top' hook did not complete for the 'form_render_skip_logic' module because of the following error:

Error Message: Uncaught Error: Unsupported operand types in /var/www/html/redcap/modules/form_render_skip_logic_v3.3.3/ExternalModule.php:307
Stack trace:
#0 /var/www/html/redcap/modules/form_render_skip_logic_v3.3.3/ExternalModule.php(370): FormRenderSkipLogic\ExternalModule\ExternalModule->getFormsAccessMatrix(28179, NULL)
#1 /var/www/html/redcap/modules/form_render_skip_logic_v3.3.3/ExternalModule.php(51): FormRenderSkipLogic\ExternalModule\ExternalModule->loadFRSL('record_home', NULL)
#2 [internal function]: FormRenderSkipLogic\ExternalModule\ExternalModule->redcap_every_page_top('5968')
#3 /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(1320): call_user_func_array(Array, Array)
#4 /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(1405): ExternalModules\ExternalModules::startHook('form_render_ski...', 'v3.3.3', Array)
#5 /var/www/html/redcap/redcap_v8.5.11/Classes/Hooks.php(37): ExternalModules\ExternalModules::callHook('every_page_top', Array)
#6 /var/www/ht
File: /var/www/html/redcap/modules/form_render_skip_logic_v3.3.3/ExternalModule.php
Line: 307

**Comment by pbchase** [comment]
@jasonlones, that for providing the error log.  We're short-staffed right now, but should be able to get to this in about 3 weeks.

**Comment by pbchase** [comment]
Fixed in PR #38
