### ISSUE TITLE
issue with repeating instruments

### ISSUE THREAD

**Issue by mschulze0** [ctsit/form_render_skip_logic#67]
Hi,

I found a bug involving having a repeating instrument and using the "Save & Go to next form" button. I hope you can replicate this.

When I'm on a repeating instrument and "Save & Go to next form" it incorrectly appends the "instance=n" parameter to call the next instrument. This is not an issue when I'm on the first instance of a repeating instrument as it calls the next instrument with instance=1, but when I'm on the second or higher instance, it will call the next instrument with instance=2, 3, etc. which completely breaks the data entry on that page if that next instrument is not actually set up as repeating.

At first I thought this was a new REDCap bug, but the bug disappeared after disabling FRSL. This even happens with a completely empty FRSL config.

**Comment by mschulze0** [comment]
Looking at your code it seems you're always calling the next instrument with "instance" as set by REDCap. For some reason when using the "Save & Go to next form" button instance is still set to the current instance of the repeating instrument. It seems like REDCap itself (when FRSL is not enabled) resets the instance parameter to 1 when using that button.

**Comment by mschulze0** [comment]
There is another issue related to this:

on the record status dashboard it displays the wrong status icons for all instruments that follow a repeating instrument and are in the same event. It shows the "Many statuses (mixed)" icon for all instruments following a repeating instrument even though these instruments aren't repeating. This bug does not occur on the record home page, but it does appear on the status dashboard and also in the side bar ("Data Collection Instruments") when I'm on a specific instrument.

**Comment by pbchase** [comment]
@mschulze0, what versions of FRSL and REDCap are you seeing this in? That sounds like issue #41 that was addressed in release 3.3.10.

**Comment by mschulze0** [comment]
@pbchase seems like #41 was kind of the opposite problem: there it wasn’t appending higher values of the instance parameter correctly whereas here it incorrectly appends higher values of it. I’m on 3.3.10.

**Comment by mschulze0** [comment]
@pbchase i guess basically FRSL should append the instance parameter (>1) when you’re in a repeating **event** whereas it shouldn’t append it when you’re on a repeating **instrument.**

**Comment by mschulze0** [comment]
@pbchase Any updates on this?

**Comment by pbchase** [comment]
@mschulze0, sorry, there's been no progress on this one. We lost a developer just before Christmas and are still working on refilling her position.

**Comment by mlurca** [comment]
@pbchase, @mschulze0

We have also recently discovered this issue in one of our REDCap project.

We were able to reproduce it. Please see attached XML file to create a test project


**Steps to reproduce the issue**

1. Create a test project using the XML skeleton provided.
2. Enable the Form Render Skip Logic module (there is no need to configure it, simply having it enabled is sufficient)
3. Add a new record to the project :

a. Complete the first form (Instrument 1), and click Save & Go To Next Form
b. Complete the second form (Repeatable Instrument 1) and click on Save & Add New Instance
c. Complete a second instance of this form and click on Save & Go To Next Form
d. Complete the third form (Instrument 2) and click on Save & Stay
e. The data should have disappear.


We were able to reproduce the issue. Please see attached XML file to create a test project: 
[bugrepeatableinstrum-2020-03-03-1637redcap.zip](https://github.com/ctsit/form_render_skip_logic/files/4287960/bugrepeatableinstrum-2020-03-03-1637redcap.zip)

**Steps to reproduce the issue**

Create a test project using the XML skeleton provided.
Enable the Form Render Skip Logic module (there is no need to configure it, simply having it enabled is sufficient)
Add a new record to the project :
a. Complete the first form (Instrument 1), and click Save & Go To Next Form
b. Complete the second form (Repeatable Instrument 1) and click on Save & Add New Instance
c. Complete a second instance of this form and click on Save & Go To Next Form
d. Complete the third form (Instrument 2) and click on Save & Stay
e. The data should have disappear.



If you try the step 3, but this time without the Form Render Skip Logic module enabled, the issue is not present.



Thank you

**Comment by pbchase** [comment]
@mlurca, I was able to verify the error using your test project and procedure. Thanks for that. The most interesting part of the test for me was that REDCap logged that it saved the data, but it can't read the data back. Here's the history:

![Screen Shot 2020-03-04 at 12 06 11 PM](https://user-images.githubusercontent.com/3356493/75904127-a3ded980-5e10-11ea-9521-037e965b700e.png)

And here's the log entry:

![Screen Shot 2020-03-04 at 12 06 33 PM](https://user-images.githubusercontent.com/3356493/75904152-ae996e80-5e10-11ea-840a-3752a2014c81.png)

There is saved data, but it carries a bogus instance ID in the pink box.

![bogus_instance_ids](https://user-images.githubusercontent.com/3356493/75904022-78f48580-5e10-11ea-9057-bd19710b9269.png)

So you can't read it back.

**Comment by mlurca** [comment]
@pbchase 
Thank you for your testing.  Yes, we got these results too.  We ran SQL scripts to clean the affected data in our production project (we set the instance back to NULL for some rows) and REDcap was able to read the data again.

To prevent the problem to reappear, we decided for now to hide the "Save and Go To Next Form" button using a hook.

Thank you

**Comment by pbchase** [comment]
I had not caught the subtlety that other workflows would not create this problem. I tested it myself and see what you mean. Replacing "Save and Go To Next Form" with "Save", then selecting the next form prevents the problem on the next form. That might explain we we have not seen that bug here in production.

**Comment by mlurca** [comment]
Yes, it is indeed a special scenario that was also not caught here during the test phase of the project

**Comment by mschulze0** [comment]
@pbchase well it might have happened on your server(s) without you noticing it. the easiest way to tell is: look for projects that have entered data in repeatable instruments, then check in the record status dashboard if there are instruments after the repeatable instrument that have data entered and are showing the three dots for repeatable instruments but aren't actually repeatable. those are the ones that have data incorrectly saved in higher instances without being repeatable.

**Comment by ChemiKyle** [comment]
The problem seems to be REDCap version dependent. Following the process outlined by @mlurca (thank you for the project XML and steps, extremely helpful) in 9.3.5, the error as described in step e does _not_ occur; however, despite marking instrument 2 as complete, a red icon is shown in the Record Status Dashboard.

**Comment by ChemiKyle** [comment]
I thought this all sounded fairly familiar, I believe this issue is likely caused by a prior commit of mine adding support repeating instances: https://github.com/ctsit/form_render_skip_logic/pull/62

The database invalidity was likely always present, but the REDCap version used in review did not display the error in the frontend.

**Comment by pbchase** [comment]
The bug is exploiting a bug in the REDCap backend that allows instance numbers to be set on fields that are not on repeating forms. 

There's a long thread in the REDCap community about this at [Green dot not appearing consistently in first event on some records - random behavior](https://community.projectredcap.org/questions/57484/green-dot-not-appearing-consistently-in-first-even.html). The REDCap bug predates FRSL PR #62 and has been "found" by other code as well. 

@taylorr4, you might want to explore this one again.

**Comment by mschulze0** [comment]
@pbchase in theory I actually like that behavior because it prevents data from getting deleted when you intentionally or accidentally set a repeating instrument to non-repeating. The data only becomes hidden and can be easily brought back by setting the instrument to repeating again.

**Comment by pbchase** [comment]
@mschulze0, I admire you glass-half-full attitude. Maybe @taylorr4 will devise a fix that makes us both happy. Can I dream? :-)

**Comment by ChemiKyle** [comment]
This bug does not appear in REDCap 9.7.7.

**Comment by mschulze0** [comment]
@ChemiKyle gone for me too on 9.7.7, nice

**Comment by taylorr4** [comment]
Maybe i *already* fixed it. ¯\_(ツ)_/¯

**Comment by pbchase** [comment]
Thanks, @taylorr4! Now I'm happy too, @mschulze0

**Comment by pbchase** [comment]
Addressed by PR #72
